spring.datasource.url={jdbc:mysql://ejercicio4-practica2.j.aivencloud.com:15402/defaultdb?sslMode=REQUIRED}
spring.datasource.username={avnadmin}
spring.datasource.password={AVNS_b0s9xlq6Bb54hIffJqg}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}